name: Build Padavan PSG1218Better
on: 
  release:
    types: [published]
 #   push:
 #    tags:
 #    - 'v*'
 #  branches: 
 #  - master
#  schedule:
#    - cron: 0 8 * * 5
 # watch:
 #   types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
    - name: Clone source code
      run: |
        git clone -b PSG1218 https://bitbucket.org/stevengan/padavan.git /opt/rt-n56u
        mkdir -p /opt/images/
    - name: Build Toolchain-mipsel
      run: |
          cd /opt/rt-n56u/toolchain-mipsel
          ./clean_toolchain_3.4.x
          ./build_toolchain_3.4.x
         
    - name: Build Firmware
      env:
        TNAME: psg1218_base
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #  cp -f configs/templates/psg1218_base.config .config
        #########################################################################################
        
        sed -i 10c\CONFIG_TOOLCHAIN_DIR=/opt/rt-n56u/toolchain-mipsel .config
        sudo ./clear_tree
        sudo ./build_firmware
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
